# Generated by Django 4.2.1 on 2023-05-24 00:45

import App.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='12345678ABCD-I', editable=False, populate_from=App.models.generar_slug),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_medica',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='12345678ABCD-I', editable=False, populate_from=App.models.generar_slug),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='12345678ABCD-I', editable=False, populate_from=App.models.generar_slug),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='12345678ABCD-I', editable=False, populate_from=App.models.generar_slug),
            preserve_default=False,
        ),
    ]
